// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/icon-styles/GeometricSymbols.tsx": () => import("../components/mockups/icon-styles/GeometricSymbols.tsx"),
  "./components/mockups/icon-styles/LucideSvg.tsx": () => import("../components/mockups/icon-styles/LucideSvg.tsx"),
  "./components/mockups/icon-styles/SolidFilled.tsx": () => import("../components/mockups/icon-styles/SolidFilled.tsx")
};
